# Generated by Django 3.1.1 on 2020-09-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('que_one', models.CharField(max_length=100)),
                ('que_two', models.CharField(max_length=100)),
            ],
        ),
    ]
